=== atmire/REF/dspace/config/item-validation-rules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="rule-categories" type="categorySet" />

  <xs:complexType name="categorySet">
    <xs:sequence>
      <xs:element type="ruleSet" name="preconditions" minOccurs="0" maxOccurs="1"/>
      <xs:element type="ruleCategory" name="category" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element type="ruleSet" name="exceptions" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ruleCategory">
    <xs:sequence>
      <xs:element type="ruleSet" name="rules" maxOccurs="1" minOccurs="0"/>
      <xs:element type="ruleSet" name="exceptions" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:int" name="ordinal" use="required"/>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="description"/>
    <xs:attribute type="xs:string" name="resolutionHint"/>
  </xs:complexType>

  <xs:complexType name="ruleDefinition">
    <xs:sequence>
      <xs:element type="ruleSet" name="preconditions" minOccurs="0" maxOccurs="1"/>
      <xs:element type="xs:string" name="field" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element type="xs:string" name="from" minOccurs="0" maxOccurs="1"/>
      <xs:element type="xs:string" name="to" minOccurs="0" maxOccurs="1"/>
      <xs:element type="xs:string" name="fieldDescription" minOccurs="0" maxOccurs="1"/>
      <xs:element type="value" name="fieldValue" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="ruleSet" name="exceptions" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="type" use="required"/>
    <xs:attribute type="xs:string" name="description"/>
    <xs:attribute type="xs:string" name="resolutionHint"/>
  </xs:complexType>

  <xs:complexType name="ruleSet">
    <xs:sequence>
      <xs:element type="ruleDefinition" name="rule" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="value">
    <xs:sequence>
      <xs:element type="xs:string" name="value" minOccurs="1" maxOccurs="1"/>
      <xs:element type="xs:string" name="description" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== atmire/REF/dspace/config/ref-validation-rules.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rule-categories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="item-validation-rules.xsd">

    <preconditions>
        <!-- The item has RIOXX type journal articles or conference proceedings -->
        <rule type="value"
              description="The REF policy for open access is only applicable to conference or journal publications."
              resolutionHint="Please change the RIOXX type of this item to Conference Paper/Proceeding/Abstract or Journal Article/Review.">
            <field>rioxxterms.type</field>
            <fieldDescription>RIOXX type</fieldDescription>
            <fieldValue>
                <value>Conference Paper/Proceeding/Abstract</value>
                <description>Conference Paper/Proceeding/Abstract</description>
            </fieldValue>
            <fieldValue>
                <value>Journal Article/Review</value>
                <description>Journal Article/Review</description>
            </fieldValue>
        </rule>

        <!-- When the item concerns a Conference proceedings it is only applicable for REF compliance when it has an International Standard Serial Number (ISSN). -->
        <rule type="notBlank"
              description="Conference proceedings are only applicable if they have an International Standard Serial Number (ISSN)"
              resolutionHint="If you want your submission to be REF applicable, please fill in the ISSN number that corresponds to the uploaded conference proceeding.">
            <preconditions>
                <rule type="value">
                    <field>rioxxterms.type</field>
                    <fieldDescription>RIOXX type</fieldDescription>
                    <fieldValue>
                        <value>Conference Paper/Proceeding/Abstract</value>
                        <description>Conference Paper/Proceeding/Abstract</description>
                    </fieldValue>
                </rule>
            </preconditions>
            <field>dc.identifier.issn</field>
            <fieldDescription>ISSN identifier</fieldDescription>
        </rule>

        <rule type="dateGreaterThanOrEqual"
              description="REF applicable submissions have to be accepted after or on 2016-04-01."
              resolutionHint="Please verify if the date of acceptance is correct.">
            <field>dcterms.dateAccepted</field>
            <fieldDescription>date of acceptance</fieldDescription>
            <fieldValue>
                <value>2016-04-01T00:00:00+01:00</value>
                <description>1 April 2016</description>
            </fieldValue>
        </rule>
    </preconditions>

    <category ordinal="1" name="Deposit Requirements"
              description="To be deposit compliant, the item must have all the correct metadata and it must have been deposited as soon after the point of acceptance as possible."
              resolutionHint="If you cannot meet the deposit requirements, then please select a deposit exception in the submission form.">
        <rules>

            <!-- Item has at least one file attached (bitstream) -->
            <rule type="countGreaterThan"
                    description="A compliant deposit must have at least one file."
                    resolutionHint="Please upload the author's accepted and final peerreviewed text to this item.">
                <field>bitstream.count</field>
                <fieldDescription>attached files</fieldDescription>
                <fieldValue>
                    <value>0</value>
                </fieldValue>
            </rule>

            <!-- The item concerns the correct RIOXX version -->
            <rule type="value"
                    description="The version of the text must be the author's accepted or the (corrected/enhanced) peerreviewed text."
                    resolutionHint="Please change the RIOXX version (rioxxterms.type) of this item to Author Manuscript (AM) or Version of Record (VoR).">
                <field>refterms.versionFCD</field>
                <fieldDescription>version of the deposited file</fieldDescription>
                <fieldValue>
                    <value>AM</value>
                    <description>Accepted Manuscript</description>
                </fieldValue>
                <fieldValue>
                    <value>P</value>
                    <description>Proof</description>
                </fieldValue>
                <fieldValue>
                    <value>VoR</value>
                    <description>Version of Record</description>
                </fieldValue>
                <fieldValue>
                    <value>CVoR</value>
                    <description>Corrected Version of Record</description>
                </fieldValue>
                <fieldValue>
                    <value>EVoR</value>
                    <description>Enhanced Version of Record</description>
                </fieldValue>
            </rule>

            <!-- The dateof first compliant deposit must be no later than three months after the dateof acceptance -->
            <rule type="dateRangeSmallerThanMonths"
                  description="The output must have been deposited as soon after the point of acceptance as possible, and no later than three months after this date."
                  resolutionHint="Please verify if the date of acceptance (dcterms.dateAccepted) is correct. If your publication was accepted before 2017-04-01, you can alternatively fill in the print publication date (dc.date.issued) or online publication date (refterms.dateFirstOnline) if the publication happened less than three months before the deposit date.">
                <from>dcterms.dateAccepted</from>
                <to>refterms.dateFCD</to>
                <fieldDescription>time between acceptance and deposit</fieldDescription>
                <fieldValue>
                    <value>3</value>
                </fieldValue>

                <!-- If the dateof acceptance is before 1st April 2017, the dateof first compliant deposit must be
                     no later than three months after the dateof first print publication or first online publication. -->
                <exceptions>
                    <rule type="dateRangeSmallerThanMonths"
                          description="During the first year of the policy (before 1 April 2017), outputs can be deposited up to three months after the date of print publication instead of the date of acceptance."
                          resolutionHint="Please verify if the date of acceptance and publication are correct. If your publication was accepted before 2017-04-01, you may also fill in the first online publication date (refterms.dateFirstOnline) if the publication happened less than three months before the deposit date.">
                        <preconditions>
                            <rule type="dateSmallerThan"
                                  description="The publication was accepted before 2017-04-01."
                                  resolutionHint="Please verify if the date of acceptance is correct.">
                                <field>dcterms.dateAccepted</field>
                                <fieldDescription>dateof acceptance</fieldDescription>
                                <fieldValue>
                                    <value>2017-04-01T23:59:59+01:00</value>
                                    <description>1 April 2017</description>
                                </fieldValue>
                            </rule>
                        </preconditions>
                        <from>dc.date.issued</from>
                        <to>refterms.dateFCD</to>
                        <fieldDescription>time between print publication and deposit</fieldDescription>
                        <fieldValue>
                            <value>3</value>
                        </fieldValue>
                    </rule>
                    <rule type="dateRangeSmallerThanMonths"
                          description="During the first year of the policy (before 1 April 2017), outputs can be deposited up to three months after the date of first online publication instead of the date of acceptance."
                          resolutionHint="Please verify if the date of acceptance and first online publication are correct. If your publication was accepted before 2017-04-01, you may also fill in the print publication date (dc.date.issued) if the publication happened less than three months before the deposit date.">
                        <preconditions>
                            <rule type="dateSmallerThan"
                                  description="The publication was accepted before 2017-04-01."
                                  resolutionHint="Please verify if the date of acceptance is correct.">
                                <field>dcterms.dateAccepted</field>
                                <fieldDescription>dateof acceptance</fieldDescription>
                                <fieldValue>
                                    <value>2017-04-01T23:59:59+01:00</value>
                                    <description>1 April 2017</description>
                                </fieldValue>
                            </rule>
                        </preconditions>
                        <from>refterms.dateFirstOnline</from>
                        <to>refterms.dateFCD</to>
                        <fieldDescription>time between first online publication and deposit</fieldDescription>
                        <fieldValue>
                            <value>3</value>
                        </fieldValue>
                    </rule>
                </exceptions>
            </rule>
        </rules>
        <exceptions>
            <rule type="value"
